name: "Format Python Code"

# Trigger the workflow on push or pull request,
# but only for the master branch
on: [push, pull_request]

jobs:
  autopep8:
    name: Check code formatting with autopep8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: autopep8
        uses: peter-evans/autopep8@v1.0.0
        with:
          args: --recursive --in-place --aggressive --aggressive .

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v2.0.0
        with:
          commit_user_name: Florian Müller-Fouarge
          commit_user_email: florian.mueller.fouarge@gmail.com
          # Required
          commit_message: autopep8 fix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
