name: "Unittests Windows"

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U pip wheel;
        pip install -r requirements/install.txt;
        pip install -r requirements/unittests.txt;
        pip install --no-deps .

    - name: Run Tests
      run: |
        coverage run -m unittest
        coverage xml # convert .coverage file to coverage.xml file

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v1.0.2
    #   with:
    #     token: ${{secrets.CODECOV_TOKEN}} #required
    #     file: ./coverage.xml #optional
    #     flags: unittests #optional
    #     name: codecov-REPO_NAME #optional
